- hosts: webservers
  tasks:
    - name: provide env
      ansible.builtin.template:
        src: .env.j2
        dest: .env
        mode: '0644'

    - name: start redmine
      community.docker.docker_container:
        name: redmine
        image: 'redmine:{{ version | default("5.0.5-alpine") }}'
        restart_policy: always
        state: started
        env_file: .env
        ports: "{{ app_port }}:3000"