- hosts: all

- name: Include terraform.yml
  ansible.builtin.import_playbook: terraform.yml

- name: Include setup.yml
  ansible.builtin.import_playbook: setup.yml

- name: Include deploy.yml
  ansible.builtin.import_playbook: deploy.yml